version: "3.7"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      - potsgresql

  potsgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
