# Generated by Django 3.2.9 on 2022-07-18 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClippedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField(blank=True, null=True, verbose_name='первоначальная ссылка')),
                ('shortened_link', models.URLField(blank=True, null=True, verbose_name='сокращенная ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='link_shortener.clippedlinks')),
                ('user', models.ForeignKey(default='deleted user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clippedlinks',
            name='creator_link',
            field=models.ManyToManyField(through='link_shortener.ThroughModel', to=settings.AUTH_USER_MODEL, verbose_name='создатель ссылки'),
        ),
    ]
